# Generated by Django 5.2.7 on 2025-10-10 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('preferencias', models.JSONField(blank=True, default=dict, verbose_name='Preferencias')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Enfermera',
                'verbose_name_plural': 'Enfermeras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=50, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Turno',
                'verbose_name_plural': 'Tipos de Turno',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('num_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(90)], verbose_name='Número de días')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('demanda_por_turno', models.JSONField(default=dict, verbose_name='Demanda por turno')),
                ('restricciones_duras', models.JSONField(default=list, verbose_name='Restricciones duras')),
                ('restricciones_blandas', models.JSONField(default=list, verbose_name='Restricciones blandas')),
                ('num_trabajadores', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Número de trabajadores paralelos')),
                ('tiempo_maximo_segundos', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)], verbose_name='Tiempo máximo en segundos')),
                ('seed', models.IntegerField(blank=True, null=True, verbose_name='Semilla aleatoria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enfermeras', models.ManyToManyField(to='turnos.enfermera', verbose_name='Enfermeras')),
                ('turnos', models.ManyToManyField(to='turnos.tipoturno', verbose_name='Turnos')),
            ],
            options={
                'verbose_name': 'Configuración de Planificación',
                'verbose_name_plural': 'Configuraciones de Planificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('es_optima', models.BooleanField(default=False, verbose_name='Es óptima')),
                ('penalizacion_total', models.FloatField(blank=True, null=True, verbose_name='Penalización total')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('mensajes', models.JSONField(blank=True, default=dict, verbose_name='Mensajes')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='turnos.configuracionplanificacion', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Ejecución',
                'verbose_name_plural': 'Ejecuciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('num_dias', models.IntegerField(verbose_name='Número de días')),
                ('ejecucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planilla_generada', to='turnos.ejecucion', verbose_name='Ejecución')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecucion_generada', to='turnos.planilla', verbose_name='Planilla'),
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('es_dia_libre', models.BooleanField(default=False, verbose_name='Es día libre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('enfermera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='turnos.enfermera', verbose_name='Enfermera')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='turnos.planilla', verbose_name='Planilla')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.tipoturno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'ordering': ['fecha', 'enfermera'],
                'unique_together': {('planilla', 'enfermera', 'fecha')},
            },
        ),
    ]
