# Generated by Django 5.2.7 on 2025-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='demanda_por_turno',
            field=models.JSONField(blank=True, default=dict, verbose_name='Demanda por turno'),
        ),
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='restricciones_blandas',
            field=models.JSONField(blank=True, default=list, verbose_name='Restricciones blandas'),
        ),
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='restricciones_duras',
            field=models.JSONField(blank=True, default=list, verbose_name='Restricciones duras'),
        ),
    ]
