# Generated by Django 5.2.7 on 2025-10-25 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_configuracionplanificacion_demanda_por_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='num_dias',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)], verbose_name='Número de días'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_creados', to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espacio de Trabajo',
                'verbose_name_plural': 'Espacios de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='turnos.workspace'),
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='turnos.workspace'),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfermeras', to='turnos.workspace'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='turnos.workspace'),
        ),
        migrations.AddField(
            model_name='tipoturno',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_turno', to='turnos.workspace'),
        ),
    ]
