# Generated by Django 5.2.7 on 2025-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_configuracionplanificacion_num_dias_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='restricciones_duras',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Restricciones duras'),
        ),
    ]
