# Generated by Django 5.2.7 on 2025-11-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_configuracionplanificacion_restricciones_duras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='restricciones_blandas',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Restricciones blandas'),
        ),
    ]
