# Generated by Django 5.2.7 on 2026-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_configuracionplanificacion_restricciones_blandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='turnos_por_dia',
            field=models.ManyToManyField(blank=True, related_name='config_turnos_por_dia', to='turnos.tipoturno', verbose_name='Turnos por día'),
        ),
    ]
