# Generated by Django 5.2.7 on 2026-01-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_configuracionplanificacion_turnos_por_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionplanificacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Configuración de Planificación', 'verbose_name_plural': 'Configuraciones de Planificación'},
        ),
        migrations.CreateModel(
            name='PatronTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('SEQ', 'Secuencia Obligatoria'), ('REST', 'Descanso Post-Turno'), ('MAX_CONS', 'Máximo Consecutivos'), ('ROT', 'Rotación Cíclica'), ('COV_MIN', 'Cobertura Mínima'), ('BLOCK', 'Transición Bloqueada'), ('EQUI', 'Distribución Equitativa')], help_text='Tipo de patrón a aplicar', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('es_restriccion_dura', models.BooleanField(default=True, help_text='Si es False, se penaliza pero no se prohíbe')),
                ('peso_penalizacion', models.IntegerField(default=100, help_text='Peso de penalización si no es restricción dura')),
                ('configuracion', models.JSONField(default=dict, help_text='\n        Configuración específica del patrón. Ejemplos:\n        \n        DESCANSO_POST_TURNO: {\n            "turno_tipo": "NOCHE",\n            "cantidad_consecutiva": 2,\n            "dias_descanso_requeridos": 3\n        }\n        \n        MAX_CONSECUTIVOS: {\n            "turno_tipo": "CUALQUIERA",  # o "NOCHE", "MAÑANA"\n            "cantidad_maxima": 5\n        }\n        \n        SECUENCIA_OBLIGATORIA: {\n            "secuencia": ["MAÑANA", "TARDE", "NOCHE"],\n            "ciclica": true\n        }\n        \n        BLOQUEO_TRANSICION: {\n            "turno_origen": "NOCHE",\n            "turno_destino": "MAÑANA",\n            "dias_minimos_entre": 1\n        }\n        \n        COBERTURA_MINIMA: {\n            "turno_tipo": "NOCHE",\n            "enfermeras_minimas": 2,\n            "aplicar_dias": [5, 6, 0]  # Vie, Sab, Dom (0=Lunes)\n        }\n        ')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrón de Turnos',
                'verbose_name_plural': 'Patrones de Turnos',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='patrones_turnos',
            field=models.ManyToManyField(blank=True, help_text='Patrones de turnos a aplicar en esta configuración', related_name='configuraciones', to='turnos.patronturnos'),
        ),
    ]
