# Generated by Django 5.2.7 on 2026-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_alter_configuracionplanificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='patrones_turnos_json',
            field=models.JSONField(blank=True, default=list, help_text='Patrones configurados dinámicamente desde el formulario', verbose_name='Patrones de turnos (JSON)'),
        ),
        migrations.AlterField(
            model_name='configuracionplanificacion',
            name='patrones_turnos',
            field=models.ManyToManyField(blank=True, help_text='Patrones predefinidos en la base de datos (legacy)', related_name='configuraciones', to='turnos.patronturnos'),
        ),
        migrations.AlterField(
            model_name='patronturnos',
            name='configuracion',
            field=models.JSONField(default=dict, help_text='\n        Configuración específica del patrón. Ejemplos:\n\n        DESCANSO_POST_TURNO: {\n            "turno_tipo": "NOCHE",\n            "cantidad_consecutiva": 2,\n            "dias_descanso_requeridos": 3\n        }\n\n        MAX_CONSECUTIVOS: {\n            "turno_tipo": "CUALQUIERA",  # o "NOCHE", "MAÑANA"\n            "cantidad_maxima": 5\n        }\n\n        SECUENCIA_OBLIGATORIA: {\n            "secuencia": ["MAÑANA", "TARDE", "NOCHE"],\n            "ciclica": true\n        }\n\n        BLOQUEO_TRANSICION: {\n            "turno_origen": "NOCHE",\n            "turno_destino": "MAÑANA",\n            "dias_minimos_entre": 1\n        }\n\n        COBERTURA_MINIMA: {\n            "turno_tipo": "NOCHE",\n            "enfermeras_minimas": 2,\n            "aplicar_dias": [5, 6, 0]  # Vie, Sab, Dom (0=Lunes)\n        }\n        '),
        ),
    ]
