# Generated by Django 5.1.15 on 2026-04-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_configuracionplanificacion_patrones_turnos_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='tipo_celda',
            field=models.CharField(choices=[('TURNO', 'Turno normal'), ('LIBRE', 'Día libre'), ('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso'), ('BAJA', 'Baja médica'), ('FORMACION', 'Formación'), ('ASIGNACION_FIJA', 'Asignación fija')], default='TURNO', max_length=20, verbose_name='Tipo de celda'),
        ),
        migrations.AlterField(
            model_name='ejecucion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('INVIABLE', 'Inviable'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ContratoEnfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semana_objetivo', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Horas semana objetivo')),
                ('horas_anuales_objetivo', models.DecimalField(decimal_places=2, default=1800.0, max_digits=6, verbose_name='Horas anuales objetivo')),
                ('porcentaje_jornada', models.DecimalField(decimal_places=2, default=100.0, help_text='100 = jornada completa, 50 = media jornada', max_digits=5, verbose_name='Porcentaje jornada')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia')),
                ('enfermera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='turnos.enfermera')),
            ],
            options={
                'verbose_name': 'Contrato de Enfermera',
                'verbose_name_plural': 'Contratos de Enfermera',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso'), ('BAJA', 'Baja médica'), ('FORMACION', 'Formación'), ('LIBRANZA_BLOQUEADA', 'Libranza bloqueada'), ('ASIGNACION_FIJA', 'Asignación fija')], max_length=30, verbose_name='Tipo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('enfermera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='turnos.enfermera')),
                ('turno_fijo', models.ForeignKey(blank=True, help_text='Para ASIGNACION_FIJA, qué turno asignar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.tipoturno', verbose_name='Turno fijo')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RotacionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ciclo_dias', models.IntegerField(help_text='Duración del ciclo en días', verbose_name='Ciclo días')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='turnos.workspace')),
            ],
            options={
                'verbose_name': 'Rotación Base',
                'verbose_name_plural': 'Rotaciones Base',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRotacionEnfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desfase', models.IntegerField(default=0, help_text='Desplazamiento en días dentro del ciclo', verbose_name='Desfase')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('enfermera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rotacion', to='turnos.enfermera')),
                ('rotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.rotacionbase')),
            ],
            options={
                'verbose_name': 'Asignación de Rotación',
                'verbose_name_plural': 'Asignaciones de Rotación',
            },
        ),
        migrations.CreateModel(
            name='BalanceHistoricoEnfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.CharField(help_text="Año o rango: '2025', '2025-H1'", max_length=20, verbose_name='Periodo referencia')),
                ('horas_acumuladas_previas', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Horas acumuladas previas')),
                ('noches_acumuladas', models.IntegerField(default=0, verbose_name='Noches acumuladas')),
                ('fines_semana_acumulados', models.IntegerField(default=0, verbose_name='Fines de semana acumulados')),
                ('festivos_acumulados', models.IntegerField(default=0, verbose_name='Festivos acumulados')),
                ('ultimo_turno_fecha', models.DateField(blank=True, null=True, verbose_name='Último turno fecha')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('enfermera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_historico', to='turnos.enfermera')),
                ('ultimo_turno_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.tipoturno', verbose_name='Último turno tipo')),
            ],
            options={
                'verbose_name': 'Balance Histórico',
                'verbose_name_plural': 'Balances Históricos',
                'unique_together': {('enfermera', 'periodo_referencia')},
            },
        ),
        migrations.CreateModel(
            name='CeldaRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Posición dentro del ciclo (0-based)', verbose_name='Orden')),
                ('es_libre', models.BooleanField(default=False, verbose_name='Es libre')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.tipoturno', verbose_name='Turno')),
                ('rotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='turnos.rotacionbase')),
            ],
            options={
                'verbose_name': 'Celda de Rotación',
                'verbose_name_plural': 'Celdas de Rotación',
                'ordering': ['orden'],
                'unique_together': {('rotacion', 'orden')},
            },
        ),
    ]
