# Generated by Django 5.1.15 on 2026-04-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_add_domain_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecucion',
            name='planilla',
        ),
        migrations.AlterField(
            model_name='balancehistoricoenfermera',
            name='enfermera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_historicos', to='turnos.enfermera'),
        ),
    ]
