# Generated by Django 5.1.15 on 2026-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_remove_ejecucion_planilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistoricoenfermera',
            name='periodo_referencia',
            field=models.CharField(help_text="Formato mensual YYYY-MM, ej. '2026-04'", max_length=20, verbose_name='Periodo referencia'),
        ),
    ]
