# Generated by Django - Add codigo_corto to TipoTurno

from django.db import migrations, models


def set_default_codigos(apps, schema_editor):
    """Asigna códigos cortos por defecto a los tipos de turno existentes."""
    TipoTurno = apps.get_model('turnos', 'TipoTurno')
    CODIGOS = {
        'MANANA': 'M',
        'TARDE': 'T',
        'NOCHE': 'N',
    }
    for turno in TipoTurno.objects.all():
        codigo = CODIGOS.get(turno.nombre, '')
        if codigo and not turno.codigo_corto:
            turno.codigo_corto = codigo
            turno.save(update_fields=['codigo_corto'])


def reverse_codigos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_balancehistoricoenfermera_periodo_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoturno',
            name='codigo_corto',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Abreviatura para planillas compactas (ej: M, T, N)',
                max_length=5,
                verbose_name='Código corto',
            ),
        ),
        migrations.RunPython(set_default_codigos, reverse_codigos),
    ]
