# Generated by Django 5.2.7 on 2026-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_tipoturno_codigo_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoturno',
            name='es_incidencia',
            field=models.BooleanField(default=False, help_text='Si es verdadero, se trata como incidencia (no se asigna automáticamente)', verbose_name='Es incidencia'),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='codigo_corto',
            field=models.CharField(help_text='Acrónimo para planillas compactas (ej: M, T, N, L, D)', max_length=5, verbose_name='Código corto'),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin (opcional para turnos como Libre o Descanso)', null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio (opcional para turnos como Libre o Descanso)', null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de turno (ej: Mañana, Tarde, Noche, Libre, Descanso)', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='tipoturno',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'nombre'), name='unique_nombre_por_workspace'),
        ),
        migrations.AddConstraint(
            model_name='tipoturno',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'codigo_corto'), name='unique_codigo_por_workspace'),
        ),
    ]
