# Generated by Django 5.2.7 on 2026-06-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_tipoturno_dinamico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoturno',
            name='es_sustituto_libre',
            field=models.BooleanField(default=False, help_text='Si es verdadero, este tipo actúa como "Libre" (0 horas, sin horario específico) en la planificación', verbose_name='Es sustituto de Libre'),
        ),
    ]
