# Generated by Django 5.1.15 on 2026-06-20 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_tipoturno_sustituto_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='horas_anuales',
            field=models.IntegerField(default=1800, help_text='Horas de trabajo por año según normativa laboral', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2500)], verbose_name='Horas anuales'),
        ),
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='horas_mensuales',
            field=models.IntegerField(default=160, help_text='Horas de trabajo por mes según normativa laboral', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Horas mensuales'),
        ),
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='horas_semanales',
            field=models.IntegerField(default=40, help_text='Horas de trabajo por semana según normativa laboral', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='Horas semanales'),
        ),
    ]
