# Generated by Django 5.1.15 on 2026-06-20 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_add_horas_laborales_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionplanificacion',
            name='horas_semanales_globales',
            field=models.IntegerField(blank=True, help_text='Total de horas semanales del equipo completo (opcional, solo informativo)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Horas semanales globales (equipo)'),
        ),
    ]
